[package]
name = "diep-rs"
version = "0.1.0"
edition = "2021"

[features]
client = []
server = []

[dependencies]
anyhow = "1.0.83"
bevy = "0.13.2"
bevy_xpbd_2d = "0.4.2"
cfg-if = "1.0.0"
lightyear = { version = "0.15.1", features = ["webtransport", "websocket", "xpbd_2d"] }
rand = "0.8.5"
serde = { version = "1.0.201", features = ["derive"] }
tracing = "0.1.40"
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = [
    "Document", 
    "Element",
    "Node",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "OffscreenCanvas",
    "OffscreenCanvasRenderingContext2d",
    "CanvasPattern",
    "Path2d",
]}
