[package]
name = "diep-rs"
version = "0.1.0"
edition = "2021"

[features]
client = []
server = []

[dependencies]
bevy = "0.13.2"
bevy_xpbd_2d = "0.4.2"
cfg-if = "1.0.0"
lightyear = { version = "0.14.1", features = [
    "webtransport",
    "websocket",
] }
rand = "0.8.5"
