[build]
target = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
rustflags = ["--cfg", "web_sys_unstable_apis"]
incremental = true




# Enable max optimizations for dependencies, but not for our code
[profile.dev.package."*"]
opt-level = 3


# Enable only a small amount of optimization in debug mode
#[profile.dev]
#opt-level = 1