[build]
#target = "wasm32-unknown-unknown"
rustflags = ["--cfg", "web_sys_unstable_apis"]

# Enable max optimizations for dependencies, but not for our code
[profile.dev.package."*"]
opt-level = 3

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1